import NextHead from 'next/head'

function Head({title}) {
  return (
    <NextHead>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
    </NextHead>
  )
}

export default Head